### ISSUE TITLE
First door in Jabu Jabu crashes 

### ISSUE THREAD

**Issue by dcvz** [dcvz/Shipwright#12]
### Issue

The first door in 'Inside Jabu Jabu's Belly' causes a crash. It works fine with OpenGL using the same otr file

https://youtu.be/REuT7syWa8E?t=56  <--- This door

**Comment by crowell** [comment]
i can't repro this, can you share repro steps?

**Comment by dcvz** [comment]
@crowell not sure it was reported here: https://github.com/dcvz/Shipwright/discussions/5#discussioncomment-3033903

maybe it's not there anymore? and was a main SoH bug?

**Comment by UltraHDR** [comment]
Thanks @dcvz @crowell for checking. I tried the latest working metal build and it no longer crashes on that door. Thanks for your hard work.
