### ISSUE TITLE
Windows Builds Compile Faster on Visual Studio

### ISSUE THREAD

**Issue by dcvz** [dcvz/Shipwright#23]
Compiling on Visual Studio is much faster than using the cake build tools on VSCode. Perhaps some flags are missing to enable multithreading?

**Comment by th-2021** [comment]
Can you provide some numbers for comparison?

**Comment by dcvz** [comment]
It's hard because I'm not the one having the issue (I don't have Windows) but apparently its a night and day difference. You can tell the difference just by running it. It takes an "eternity" when not going through Visual Studio.

**Comment by th-2021** [comment]
on the development channel the talk is between 5 nad 10 minutes. That doesn't sound like eternity.
